<%@ Page Title="" Language="C#" MasterPageFile="~/Menu.Master" AutoEventWireup="true" CodeBehind="RutinasAdmin.aspx.cs" Inherits="ProyectoGym.RutinasAdmin" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link href="Estilos/EstiloGrid.css" rel="stylesheet" />
    <link href="Estilos/EstilosBotones.css" rel="stylesheet" />
    <style type="text/css">
        .auto-style1 {
            text-align: center;
        }
        .auto-style3 {
            font-weight: bold;
            color: #FFFFFF;
            background-color: #808080;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <p>
        <br />
    </p>
    <p class="auto-style1">
&nbsp;<asp:Image ID="Image1" runat="server" Height="230px" ImageAlign="Top" Width="380px" ImageUrl="~/Imagenes/Training-In-Saiyan-Gym-To-Beat-Goku.jpg" />
    </p>
    <p class="auto-style1">
        <asp:GridView ID="datagrid1" runat="server" AllowPaging="false" AutoGenerateDeleteButton="false" AutoGenerateEditButton="false" AutoGenerateSelectButton="false" CssClass="auto-style10" HeaderStyle-CssClass="header" PagerStyle-CssClass="pager" RowStyle-CssClass="rows" Height="197px" Width="1064px">
            </asp:GridView></p>
    <p>&nbsp; </p>
    <p><strong>NOMBRE RUTINA:&nbsp;</strong>&nbsp; <strong>
        <asp:TextBox ID="txtRutina" runat="server" CssClass="auto-style3"></asp:TextBox>
        </strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <strong>NÚMERO DE SERIES:&nbsp;</strong> <strong>
        <asp:TextBox ID="txtSeries" runat="server" CssClass="auto-style3"></asp:TextBox>
        </strong></p>
    <br />
    <br />
    <asp:Button ID="btnAgregar" class="button button3" runat="server" Text="AGREGAR" OnClick="btnAgregar_Click" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;<asp:Button ID="btnBorrar" class="button button3" runat="server" Text="BORRAR" OnClick="btnBorrar_Click" />
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;<asp:Button ID="btnActualizar" runat="server" class="button button3" Text="ACTUALIZAR" OnClick="btnActualizar_Click" /><p>
        &nbsp;</p>
    <p>
        &nbsp;</p>
    <p>
        &nbsp;</p>
</asp:Content>
