<%@ Page Title="" Language="C#" MasterPageFile="~/Menu2.Master" AutoEventWireup="true" CodeBehind="RutinasReg.aspx.cs" Inherits="ProyectoGym.RutinasReg" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link href="Estilos/EstiloGrid.css" rel="stylesheet" />
    <style type="text/css">
        .auto-style1 {
            text-align: center;
        }
        .auto-style2 {
            color: #000000;
            text-align: center;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <p>
        <br />
    </p>
    <p class="auto-style2">
        <strong>LISTA DE RUTINA </strong>
    </p>
    <p class="auto-style1">
        <asp:Image ID="Image1" runat="server" Height="343px" ImageUrl="~/Imagenes/1717561_1.jpg" Width="450px" />
    </p>
    <p class="auto-style1">
        <asp:GridView ID="datagrid1" runat="server" AllowPaging="false" AutoGenerateDeleteButton="false" AutoGenerateEditButton="false" AutoGenerateSelectButton="false" CssClass="auto-style10" HeaderStyle-CssClass="header" PagerStyle-CssClass="pager" RowStyle-CssClass="rows" Height="197px" Width="1064px" >
            </asp:GridView></p>&nbsp;
    
    <p class="auto-style1">
        &nbsp;</p>
</asp:Content>
